services:

    # Service 1
    service1-php:
        container_name: service1-php
        build:
            context: .
            dockerfile: Dockerfile
            target: dev
        working_dir: /app
        volumes:
            - .:/app
        networks:
            - circuit-breaker-demo

    service1-nginx:
        container_name: service1-nginx
        image: nginx:1.27.3-alpine3.20
        ports:
            - "9080:80"
        volumes:
            - ./docker/nginx/conf.d/default1.conf:/etc/nginx/conf.d/default.conf:ro
            - ./public:/app/public
        networks:
            - circuit-breaker-demo

    # Service 2
    service2-php:
        container_name: service2-php
        build:
            context: .
            dockerfile: Dockerfile
            target: dev
        working_dir: /app
        volumes:
            - .:/app
        networks:
            - circuit-breaker-demo

    service2-nginx:
        container_name: service2-nginx
        image: nginx:1.27.3-alpine3.20
        ports:
            - "9090:80"
        volumes:
            - ./docker/nginx/conf.d/default2.conf:/etc/nginx/conf.d/default.conf:ro
            - ./public:/app/public
        networks:
            - circuit-breaker-demo

    redis:
        image: redis:7.4.2-alpine3.21
        container_name: redis
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data
        networks:
            - circuit-breaker-demo

networks:
    circuit-breaker-demo:
        driver: bridge
volumes:
    redis-data:
